### Numpy


Numpy:- Numpy stands for numerical python and is the core library for numeric and scientific computing, It consists of multi-dimensional array objects

Its an homogeneous in nature the numpy list contains single datatype
The array which we are using doesnot supports multi-dimensional, It only allows 1(single dimension).
So to work on multi-dimension array we use 3rd party package called Numpy

In [1]:
!pip install numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 23.2.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
np.__version__

'1.18.2'

In [6]:
a = np.array([3,4,5.6,9],dtype="int32")
print(a)
type(a)

[3 4 5 9]


numpy.ndarray

In [7]:
# Getting the dimensions
print(a.ndim)
#ndim is used to find the dimension of the array

1


In [8]:
a1 = np.array([[2,3,4,5,6],[4,6,8,0,4]])
print(a1)
# Getting the shape of the array
print(a1.ndim)
print(type(a1))
#shape is used to find out the no. of rows & columns in the array
a1.shape

[[2 3 4 5 6]
 [4 6 8 0 4]]
2
<class 'numpy.ndarray'>


(2, 5)

In [9]:
b = np.array([[[3,4,5,6,6,7],[6,6,9,0,16,7]],
              [[3,6,66,90,34,3],[34,22,1,3,2,3]],
              [[5,6,7,1,1,1],[2,3,4,1,3,4]]],dtype="float32")
print(b)
print(b.ndim)
print(b.shape)
# 3 is no. of sets, 2 = no.of rows & 6= no. of columns

[[[ 3.  4.  5.  6.  6.  7.]
  [ 6.  6.  9.  0. 16.  7.]]

 [[ 3.  6. 66. 90. 34.  3.]
  [34. 22.  1.  3.  2.  3.]]

 [[ 5.  6.  7.  1.  1.  1.]
  [ 2.  3.  4.  1.  3.  4.]]]
3
(3, 2, 6)


### Indexing and Slicing

In [10]:
x = np.array([[2,3,4],[5,9,0],[2,8,7],[3,1,6]])
print(x)
print(x[1,2])
print()
print(x[3,0])
print()
print(x[2,2])
print()
print(x[0:2,0])
print()
print(x[:,2])
print()
print(x[2,:])
print()
print(x[0, ::2])

[[2 3 4]
 [5 9 0]
 [2 8 7]
 [3 1 6]]
0

3

7

[2 5]

[4 0 7 6]

[2 8 7]

[2 4]


In [11]:
import numpy as np
a=np.array([[1,2,3,4],[3,4,5,6],[8,9,10,11]])
print(a)
print(a[2,0])
print(a[:,2])
print(a[0:2,:])

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
8
[ 3  5 10]
[[1 2 3 4]
 [3 4 5 6]]


In [12]:
import numpy as np
b = np.array([[[1,3],[3,4]],[[5,6],[7,8]]],dtype='int64')
print(b)
print(b.ndim)

[[[1 3]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [13]:
print(b[0,1,1])

4


In [14]:
print(b[:,1,:])

[[3 4]
 [7 8]]


### Initializing Different Types of Arrays

In [15]:
x = np.ones((2,2,5),dtype='int32')
print(x)
print(x.ndim)

a=np.ones((3,3))
print(a)
print(a.ndim)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [16]:
a = np.zeros((1,5))
print(a)
print(a.shape)
print(a.ndim)

import warnings
warnings.filterwarnings("ignore")
print(np.zeros((2,3),dtype=np.int))

[[0. 0. 0. 0. 0.]]
(1, 5)
2
[[0 0 0]
 [0 0 0]]


In [17]:
c = np.full((3,4),12)
print(c)
print()

print(np.full((2,5),3.6))

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]

[[3.6 3.6 3.6 3.6 3.6]
 [3.6 3.6 3.6 3.6 3.6]]


In [18]:
b = np.identity(3)
print(b)
print()
print(np.identity(5,dtype=np.int))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [19]:
#np.random.seed(10)
#it is used to get fixed output everytime

a=np.linspace(0,40,9)
#linspace is used if I want to divide my range into
#n no.of parts
print(a)
print()

a=np.arange(1,121,2).reshape(10,6)
# it works by creating step difference in your given range
print(a)

a=np.random.random((3,4))
#randomnly creates an array of desired range most
#of the times it is between 0-1
print(a)

a=np.random.randint(50,101,(3,4))
# randomly creates an array of desired range & the arrays
#consists of integer datatype in the given range.
print(a)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40.]

[[  1   3   5   7   9  11]
 [ 13  15  17  19  21  23]
 [ 25  27  29  31  33  35]
 [ 37  39  41  43  45  47]
 [ 49  51  53  55  57  59]
 [ 61  63  65  67  69  71]
 [ 73  75  77  79  81  83]
 [ 85  87  89  91  93  95]
 [ 97  99 101 103 105 107]
 [109 111 113 115 117 119]]
[[0.22669026 0.41998047 0.82535457 0.76539173]
 [0.06254506 0.24115746 0.19580544 0.34336246]
 [0.21453261 0.77232751 0.91202505 0.56121   ]]
[[95 81 52 63]
 [66 66 84 75]
 [83 68 93 74]]


In [20]:
#np.random.seed(10)
#uniform helps to give the float output from the given range
a=np.random.uniform(50,100,(2,2,3))
print(a)

[[[97.97243408 93.11607994 89.44696515]
  [94.82384327 70.49128098 90.94066216]]

 [[73.18519097 86.01502815 79.85463308]
  [90.77158204 97.00396492 66.50770449]]]


In [21]:
#aggregate functions
a=np.array([[8,9],[10,11],[12,13]])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(np.mean(a))

8
13
63
10.5
10.5


In [22]:
#math functions
a=np.array([[1,0,3],[3,4,5]])

print(np.sqrt(a))
print(np.std(a))
print(np.log(a))
b=np.sqrt(a)
print(b.round(2))
print(b.round(4))

[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]
1.699673171197595
[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]
[[1.   0.   1.73]
 [1.73 2.   2.24]]
[[1.     0.     1.7321]
 [1.7321 2.     2.2361]]


In [23]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[3,4]])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x@y)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [24]:
x=np.array([(1,2,3),(3,4,5)])
x[0,1]=7
print(x)

x[:,2] = [1,2]
print(x)

[[1 7 3]
 [3 4 5]]
[[1 7 1]
 [3 4 2]]


In [25]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [27]:
print(x)

[[1 7 1]
 [3 4 2]]


In [28]:
print(x.ravel())                #ravel puts the 2d 3d in 1d

[1 7 1 3 4 2]


In [29]:
print(x.reshape((3,2)))

[[1 7]
 [1 3]
 [4 2]]
